// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Naruto_Hand_Sign",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Naruto_Hand_Sign",
            targets: ["AppModule"],
            bundleIdentifier: "com.academy.Naruto-Hand-Sign",
            teamIdentifier: "6MSG95SWBW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires camera access to recognize hand signs for performing jutsu.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("MLFile/HandSignDetection.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)